name: Build and Deploy Node.js Express App to Azure Web App - selfregulator-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: npm install, build, and test in backend folder
        run: |
          cd backend
          npm install
          npm run build --if-present

      - name: Archive files
        run: |
          cd backend
          powershell -command "Compress-Archive -Path * -DestinationPath ../backend.zip"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ../backend.zip # Upload the ZIP file

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "selfregulator-api"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A3DB5EDF55EA4895B6E642CFBFA78483 }}
          package: backend.zip # Use the ZIP file for deployment
          startUpCommand: "npm run start" # Specify the startup command
